---
version: '3'
services:
  conceptql:
    depends_on:
    - lexicon
    - test_data
    environment:
    - CONCEPTQL_DATA_MODEL=gdm
    - CONCEPTQL_ENABLE_COMMENTS
    - CONCEPTQL_OVERWRITE_TEST_RESULTS
    - CONCEPTQL_PRINT_SQL
    - CONCEPTQL_STOP_ON_ERROR
    - SEQUELIZER_URL=postgres://ryan:r@test_data/test_data_for_chisel
    - LEXICON_URL=postgres://ryan:r@lexicon/lexicon
    - SEQUELIZER_RETRIES=12
    - SEQUELIZER_RETRY_DELAY=5
    image: outcomesinsights/misc:conceptql.master.latest
    build:
      context: "."
      dockerfile: dockers/standard/Dockerfile
    command: sh -c "bundle && bundle exec ruby test/all.rb"
    volumes:
    - "${PWD}:/home/conceptql"
  lexicon:
    image: outcomesinsights/lexicon:forge.latest
    expose:
      - 5432
  test_data:
    image: outcomesinsights/misc:test_data.main.postgres.latest
    expose:
      - 5432
